### ISSUE TITLE
Jest not allowing imports

### ISSUE THREAD

**Issue by VadneyK** [PlasmNetwork/dusty-faucet#17]
kentarovadney@Kentaros-MacBook-Air app % yarn test
yarn run v1.22.10
warning ../../../../package.json: No license field
$ NODE_ENV=test jest --setupFiles dotenv/config --verbose --coverage && eslint '*/**/*.{js,ts,tsx}' --experimental-vm-modules
 FAIL  tests/sample.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api/index.js:3
    import "./detectPackage.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import type { RegistryTypes } from '@polkadot/types/types';
      5 | import typeDefs from '@plasm/types';
    > 6 | import { WsProvider, ApiPromise } from '@polkadot/api';
        | ^
      7 | import { client } from '../app';
      8 | // set up polkadot api
      9 | async function polkadotApi() {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (src/helpers/messageHandler.ts:6:1)

 FAIL  tests/sample.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api/index.js:3
    import "./detectPackage.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { Keyring } from '@polkadot/api';
        | ^
      2 | import type { ISubmittableResult } from '@polkadot/types/types';
      3 | import { ContractPromise } from '@polkadot/api-contract';
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (src/helpers/sendTokens.ts:1:1)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.921 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
kentarovadney@Kentaros-MacBook-Air app %

**Comment by VadneyK** [comment]
why would I need to run node? https://jestjs.io/docs/ecmascript-modules

**Comment by VadneyK** [comment]
code on this branch: https://github.com/PlasmNetwork/dusty-faucet/tree/tests-and-flow

**Comment by VadneyK** [comment]
latest branch won't let me export now? The jest configurations are a lot more complicated than anticipated:

kentarovadney@Kentaros-MacBook-Air app % yarn test
yarn run v1.22.10
warning ../../../../package.json: No license field
$ jest
 FAIL  tests/messageHandler.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kentarovadney/Desktop/code/dusty-faucet/app/src/helpers/index.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * as Api from './sendTokens';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { messageHandler } from '../src/helpers/messageHandler';
        |                 ^
      2 | describe('Message Handler', () => {
      3 |     const message = {
      4 |         channel: {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (tests/messageHandler.test.ts:1:17)

 FAIL  tests/messageHandler.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kentarovadney/Desktop/code/dusty-faucet/app/src/helpers/messageHandler.ts:4
    import type { RegistryTypes } from '@polkadot/types/types';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { messageHandler } from '../src/helpers/messageHandler';
        | ^
      2 | describe('Message Handler', () => {
      3 |     const message = {
      4 |         channel: {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (tests/messageHandler.test.ts:1:1)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.178 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by VadneyK** [comment]
Hmm this comment sort of sums up my confusion here: https://dev.to/ozaytsev86/jest-syntaxerror-unexpected-token-export-3glh

**Comment by VadneyK** [comment]
also when I dont include:["tests"] in package.json I get these red lines in vscode but everything seems to compile fine. not sure if this is an issue.

![Screen Shot 2021-06-22 at 8 50 48 PM](https://user-images.githubusercontent.com/57117207/123032852-93eb6000-d39b-11eb-8790-2cc32ac625f4.png)

**Comment by hoonsubin** [comment]
please change all imports to use the `import` instead of `require`. And remove all `any` type params. I can help you after those are addressed.

**Comment by VadneyK** [comment]
ok, just removed all `require` and `any` from the code in the latest `tests-and-flow` branch and am still getting the same errors:

kentarovadney@Kentaros-MacBook-Air app % yarn test
yarn run v1.22.10
warning ../../../../package.json: No license field
$ jest --env=jsdom --setupFiles dotenv/config --verbose --coverage && eslint '*/**/*.{js,ts,tsx}'
 FAIL  tests/messageHandler.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api/index.js:3
    import "./detectPackage.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { Keyring } from '@polkadot/api';
        | ^
      2 | import type { ISubmittableResult } from '@polkadot/types/types';
      3 | import { ContractPromise } from '@polkadot/api-contract';
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (src/helpers/sendTokens.ts:1:1)

 FAIL  tests/messageHandler.test.ts
  ● Test suite failed to run

    TypeError: TextDecoder is not a constructor

      1 | const prefix = '/';
    > 2 | import Discord, { Message, TextChannel } from 'discord.js';
        | ^
      3 |
      4 | import type { RegistryTypes } from '@polkadot/types/types';
      5 | import typeDefs from '@plasm/types';

      at Object.<anonymous> (node_modules/discord.js/src/WebSocket.js:22:12)
      at Object.<anonymous> (node_modules/discord.js/src/client/voice/networking/VoiceWebSocket.js:4:19)
      at Object.<anonymous> (node_modules/discord.js/src/client/voice/VoiceConnection.js:5:24)
      at Object.<anonymous> (node_modules/discord.js/src/client/voice/ClientVoiceManager.js:4:25)
      at Object.<anonymous> (node_modules/discord.js/src/client/Client.js:5:28)
      at Object.<anonymous> (node_modules/discord.js/src/index.js:8:11)
      at Object.<anonymous> (src/helpers/messageHandler.ts:2:1)
      at Object.<anonymous> (tests/messageHandler.test.ts:2:1)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.59 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hoonsubin** [comment]
@VadneyK I fixed the ESM import syntax for Jest TypeScript in this commit https://github.com/PlasmNetwork/dusty-faucet/commit/077a05946ac82641ee67dd3fa4d199dfc5c5749b. However, there is a coding problem with the command stack https://github.com/PlasmNetwork/dusty-faucet/blob/87163ba67872d7f602fce7a1b8e6ded6bddc7b50/app/src/helpers/messageHandler.ts#L49 that will prevent the test from passing.
You are trying to instantiate `Discord.Collection()` with the `new` keyword, but `Discord.Collection()` is a generic class that does not have a constructor. So this will never have show expected behavior.

Plus, you are overriding the `discord.js` package in here https://github.com/PlasmNetwork/dusty-faucet/blob/87163ba67872d7f602fce7a1b8e6ded6bddc7b50/app/src/helpers/discord.d.ts#L4, which is making the entire package type messy. Please remove `discord.d.ts`, fix the `cooldowns` property. Instead of using a nested collection, just use an array.

Please fix all the style issues as well

**Comment by VadneyK** [comment]
Thanks! I fixed up the issues noted above and pushed to the same branch, but now I am back with the same import issues:

kentarovadney@Kentaros-MacBook-Air app % yarn test
yarn run v1.22.10
warning ../../../../package.json: No license field
$ jest --env=jsdom --setupFiles dotenv/config --verbose --coverage && eslint '*/**/*.{js,ts,tsx}'
 FAIL  tests/messageHandler.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api/index.js:3
    import "./detectPackage.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import type { RegistryTypes } from '@polkadot/types/types';
      3 | import typeDefs from '@plasm/types';
    > 4 | import { WsProvider, ApiPromise } from '@polkadot/api';
        | ^
      5 | import { client } from '../app';
      6 | import { commands } from '../app';
      7 | import { cooldowns } from '../app';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (src/helpers/messageHandler.ts:4:1)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.416 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
kentarovadney@Kentaros-MacBook-Air app %

**Comment by VadneyK** [comment]
Also my linter still won't recognize the jest environment variables and functions that are present ;( why is this happening?

![Screen Shot 2021-06-24 at 11 16 54 AM](https://user-images.githubusercontent.com/57117207/123312830-b08fb100-d4dd-11eb-9b32-29406f602fdf.png)

**Comment by hoonsubin** [comment]
I've played around with the settings and added ESM import support flag for node when running jest. At least from my side, this fixed the issue.

```bash
 FAIL  tests/messageHandler.test.ts
  ● Test suite failed to run

    ReferenceError: exports is not defined

      1 | import { jest } from '@jest/globals';
    > 2 | import { Message } from 'discord.js';
        |                       ^
      3 | import { messageHandler } from '../src/helpers/messageHandler';
      4 |
      5 | describe('Message Handler', () => {

      at tests/messageHandler.test.ts:2:23
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.11 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

We just need to fix this issue which is caused most likely because all unit tests will ignore `node_module` file by default (which it should). Please remove the type casting here https://github.com/PlasmNetwork/dusty-faucet/blob/tests-and-flow/app/tests/messageHandler.test.ts#L18

**Comment by hoonsubin** [comment]
```bash
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
```

This is error is most likely related to the `jest` config or `tsconfig.json`

**Comment by VadneyK** [comment]
the jest tests run the raw .ts file in src/ which use .js import statements and I'm not allowed to do .ts imports 

![Screen Shot 2021-06-25 at 6 50 37 PM](https://user-images.githubusercontent.com/57117207/123498670-444ca480-d5e6-11eb-92fb-a221ab2655b1.png)

so I'm changing the place where I import to build/ but then I get this error. What is it saying that has any type implicitly? the message handler is a function with typed arguments so It has to be typed.

![Screen Shot 2021-06-25 at 6 53 58 PM](https://user-images.githubusercontent.com/57117207/123498766-b624ee00-d5e6-11eb-9555-ee61990d7176.png)

so I set noImplicitAny to false even though it's bad practice just to see what happens, then I get the following error, but I put a try/catch on all .get() statements and I'm still having the same issue:

![Screen Shot 2021-06-25 at 6 55 15 PM](https://user-images.githubusercontent.com/57117207/123498800-e2406f00-d5e6-11eb-9d48-73ba16127a30.png)

also when I do yarn start I get the follwoing issue.  changed the import statement to `import * as <name> from '...'` but It's giving me the same error

![Screen Shot 2021-06-25 at 6 56 23 PM](https://user-images.githubusercontent.com/57117207/123498835-0a2fd280-d5e7-11eb-9f81-42fbe549956e.png)

It seems that the ts.config.json changed might have introduced new issues. Now we have all the imports unified and no any types used but why is it not still working? 

Also for the Message mock object, do I have to define the entire struct in order to use it? I cased the Message mock as unknown as Message so that I could just fill up the information I will be using. Or is there some other way to do this?

![Screen Shot 2021-06-25 at 7 00 07 PM](https://user-images.githubusercontent.com/57117207/123498898-9215dc80-d5e7-11eb-8cbc-002249176d4a.png)
